// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.6.1
// source: internal/app/grpc/proto/common.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Date struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Utc int64  `protobuf:"varint,1,opt,name=utc,proto3" json:"utc,omitempty"`
	Rfc string `protobuf:"bytes,2,opt,name=rfc,proto3" json:"rfc,omitempty"`
}

func (x *Date) Reset() {
	*x = Date{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_grpc_proto_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_grpc_proto_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_internal_app_grpc_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *Date) GetUtc() int64 {
	if x != nil {
		return x.Utc
	}
	return 0
}

func (x *Date) GetRfc() string {
	if x != nil {
		return x.Rfc
	}
	return ""
}

var File_internal_app_grpc_proto_common_proto protoreflect.FileDescriptor

var file_internal_app_grpc_proto_common_proto_rawDesc = []byte{
	0x0a, 0x24, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x74, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x75, 0x74, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x66, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x66, 0x63, 0x42, 0x19, 0x5a, 0x17, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_app_grpc_proto_common_proto_rawDescOnce sync.Once
	file_internal_app_grpc_proto_common_proto_rawDescData = file_internal_app_grpc_proto_common_proto_rawDesc
)

func file_internal_app_grpc_proto_common_proto_rawDescGZIP() []byte {
	file_internal_app_grpc_proto_common_proto_rawDescOnce.Do(func() {
		file_internal_app_grpc_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_app_grpc_proto_common_proto_rawDescData)
	})
	return file_internal_app_grpc_proto_common_proto_rawDescData
}

var file_internal_app_grpc_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_app_grpc_proto_common_proto_goTypes = []interface{}{
	(*Date)(nil), // 0: proto.Date
}
var file_internal_app_grpc_proto_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_app_grpc_proto_common_proto_init() }
func file_internal_app_grpc_proto_common_proto_init() {
	if File_internal_app_grpc_proto_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_app_grpc_proto_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Date); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_app_grpc_proto_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_app_grpc_proto_common_proto_goTypes,
		DependencyIndexes: file_internal_app_grpc_proto_common_proto_depIdxs,
		MessageInfos:      file_internal_app_grpc_proto_common_proto_msgTypes,
	}.Build()
	File_internal_app_grpc_proto_common_proto = out.File
	file_internal_app_grpc_proto_common_proto_rawDesc = nil
	file_internal_app_grpc_proto_common_proto_goTypes = nil
	file_internal_app_grpc_proto_common_proto_depIdxs = nil
}
