// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.6.1
// source: internal/app/grpc/proto/season.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Season struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsCurrent *wrappers.BoolValue `protobuf:"bytes,3,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
}

func (x *Season) Reset() {
	*x = Season{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_grpc_proto_season_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Season) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Season) ProtoMessage() {}

func (x *Season) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_grpc_proto_season_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Season.ProtoReflect.Descriptor instead.
func (*Season) Descriptor() ([]byte, []int) {
	return file_internal_app_grpc_proto_season_proto_rawDescGZIP(), []int{0}
}

func (x *Season) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Season) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Season) GetIsCurrent() *wrappers.BoolValue {
	if x != nil {
		return x.IsCurrent
	}
	return nil
}

var File_internal_app_grpc_proto_season_proto protoreflect.FileDescriptor

var file_internal_app_grpc_proto_season_proto_rawDesc = []byte{
	0x0a, 0x24, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x26, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x09, 0x69, 0x73, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x32, 0xa2,
	0x01, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4e, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x46, 0x6f,
	0x72, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x65,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x41, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x46, 0x6f,
	0x72, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65,
	0x61, 0x6d, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x19, 0x5a, 0x17, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_app_grpc_proto_season_proto_rawDescOnce sync.Once
	file_internal_app_grpc_proto_season_proto_rawDescData = file_internal_app_grpc_proto_season_proto_rawDesc
)

func file_internal_app_grpc_proto_season_proto_rawDescGZIP() []byte {
	file_internal_app_grpc_proto_season_proto_rawDescOnce.Do(func() {
		file_internal_app_grpc_proto_season_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_app_grpc_proto_season_proto_rawDescData)
	})
	return file_internal_app_grpc_proto_season_proto_rawDescData
}

var file_internal_app_grpc_proto_season_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_app_grpc_proto_season_proto_goTypes = []interface{}{
	(*Season)(nil),                   // 0: proto.Season
	(*wrappers.BoolValue)(nil),       // 1: google.protobuf.BoolValue
	(*SeasonCompetitionRequest)(nil), // 2: proto.SeasonCompetitionRequest
	(*TeamSeasonsRequest)(nil),       // 3: proto.TeamSeasonsRequest
}
var file_internal_app_grpc_proto_season_proto_depIdxs = []int32{
	1, // 0: proto.Season.is_current:type_name -> google.protobuf.BoolValue
	2, // 1: proto.SeasonService.GetSeasonsForCompetition:input_type -> proto.SeasonCompetitionRequest
	3, // 2: proto.SeasonService.GetSeasonsForTeam:input_type -> proto.TeamSeasonsRequest
	0, // 3: proto.SeasonService.GetSeasonsForCompetition:output_type -> proto.Season
	0, // 4: proto.SeasonService.GetSeasonsForTeam:output_type -> proto.Season
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_app_grpc_proto_season_proto_init() }
func file_internal_app_grpc_proto_season_proto_init() {
	if File_internal_app_grpc_proto_season_proto != nil {
		return
	}
	file_internal_app_grpc_proto_requests_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internal_app_grpc_proto_season_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Season); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_app_grpc_proto_season_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_app_grpc_proto_season_proto_goTypes,
		DependencyIndexes: file_internal_app_grpc_proto_season_proto_depIdxs,
		MessageInfos:      file_internal_app_grpc_proto_season_proto_msgTypes,
	}.Build()
	File_internal_app_grpc_proto_season_proto = out.File
	file_internal_app_grpc_proto_season_proto_rawDesc = nil
	file_internal_app_grpc_proto_season_proto_goTypes = nil
	file_internal_app_grpc_proto_season_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SeasonServiceClient is the client API for SeasonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SeasonServiceClient interface {
	GetSeasonsForCompetition(ctx context.Context, in *SeasonCompetitionRequest, opts ...grpc.CallOption) (SeasonService_GetSeasonsForCompetitionClient, error)
	GetSeasonsForTeam(ctx context.Context, in *TeamSeasonsRequest, opts ...grpc.CallOption) (SeasonService_GetSeasonsForTeamClient, error)
}

type seasonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeasonServiceClient(cc grpc.ClientConnInterface) SeasonServiceClient {
	return &seasonServiceClient{cc}
}

func (c *seasonServiceClient) GetSeasonsForCompetition(ctx context.Context, in *SeasonCompetitionRequest, opts ...grpc.CallOption) (SeasonService_GetSeasonsForCompetitionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SeasonService_serviceDesc.Streams[0], "/proto.SeasonService/GetSeasonsForCompetition", opts...)
	if err != nil {
		return nil, err
	}
	x := &seasonServiceGetSeasonsForCompetitionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SeasonService_GetSeasonsForCompetitionClient interface {
	Recv() (*Season, error)
	grpc.ClientStream
}

type seasonServiceGetSeasonsForCompetitionClient struct {
	grpc.ClientStream
}

func (x *seasonServiceGetSeasonsForCompetitionClient) Recv() (*Season, error) {
	m := new(Season)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *seasonServiceClient) GetSeasonsForTeam(ctx context.Context, in *TeamSeasonsRequest, opts ...grpc.CallOption) (SeasonService_GetSeasonsForTeamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SeasonService_serviceDesc.Streams[1], "/proto.SeasonService/GetSeasonsForTeam", opts...)
	if err != nil {
		return nil, err
	}
	x := &seasonServiceGetSeasonsForTeamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SeasonService_GetSeasonsForTeamClient interface {
	Recv() (*Season, error)
	grpc.ClientStream
}

type seasonServiceGetSeasonsForTeamClient struct {
	grpc.ClientStream
}

func (x *seasonServiceGetSeasonsForTeamClient) Recv() (*Season, error) {
	m := new(Season)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SeasonServiceServer is the server API for SeasonService service.
type SeasonServiceServer interface {
	GetSeasonsForCompetition(*SeasonCompetitionRequest, SeasonService_GetSeasonsForCompetitionServer) error
	GetSeasonsForTeam(*TeamSeasonsRequest, SeasonService_GetSeasonsForTeamServer) error
}

// UnimplementedSeasonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSeasonServiceServer struct {
}

func (*UnimplementedSeasonServiceServer) GetSeasonsForCompetition(*SeasonCompetitionRequest, SeasonService_GetSeasonsForCompetitionServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSeasonsForCompetition not implemented")
}
func (*UnimplementedSeasonServiceServer) GetSeasonsForTeam(*TeamSeasonsRequest, SeasonService_GetSeasonsForTeamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSeasonsForTeam not implemented")
}

func RegisterSeasonServiceServer(s *grpc.Server, srv SeasonServiceServer) {
	s.RegisterService(&_SeasonService_serviceDesc, srv)
}

func _SeasonService_GetSeasonsForCompetition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SeasonCompetitionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SeasonServiceServer).GetSeasonsForCompetition(m, &seasonServiceGetSeasonsForCompetitionServer{stream})
}

type SeasonService_GetSeasonsForCompetitionServer interface {
	Send(*Season) error
	grpc.ServerStream
}

type seasonServiceGetSeasonsForCompetitionServer struct {
	grpc.ServerStream
}

func (x *seasonServiceGetSeasonsForCompetitionServer) Send(m *Season) error {
	return x.ServerStream.SendMsg(m)
}

func _SeasonService_GetSeasonsForTeam_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TeamSeasonsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SeasonServiceServer).GetSeasonsForTeam(m, &seasonServiceGetSeasonsForTeamServer{stream})
}

type SeasonService_GetSeasonsForTeamServer interface {
	Send(*Season) error
	grpc.ServerStream
}

type seasonServiceGetSeasonsForTeamServer struct {
	grpc.ServerStream
}

func (x *seasonServiceGetSeasonsForTeamServer) Send(m *Season) error {
	return x.ServerStream.SendMsg(m)
}

var _SeasonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SeasonService",
	HandlerType: (*SeasonServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSeasonsForCompetition",
			Handler:       _SeasonService_GetSeasonsForCompetition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSeasonsForTeam",
			Handler:       _SeasonService_GetSeasonsForTeam_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/app/grpc/proto/season.proto",
}
