version: 2.1

references:
  workspace_root: &workspace_root
                    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    working_directory: ~/go/src/github.com/statistico/statistico-web-gateway
    machine: true
    environment:
      GOPATH: /home/circleci/go
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Build Release Image
          command: |
            docker-compose -f docker-compose.build.yml up -d --build
      - run:
          name: Test Release Image
          command: |
            docker-compose -f docker-compose.build.yml run test gotestsum -f short-verbose


